### ISSUE TITLE
Export BDD

### ISSUE THREAD

**Issue by adricen** [fiascoo/site-cv#1]
### Salut Fiascoo

Tu pourrais exporter ta bdd stp?

Comme ça je pourrais intervenir sur ton projet et te filer coups de mains et conseil 

Merci ;)

**Comment by fiascoo** [comment]
[site-cv.zip](https://github.com/fiascoo/site-cv/files/725273/site-cv.zip)

**Comment by adricen** [comment]
### Ok parfait!
